#!/bin/bash
# 
# OWL Reasoner Evaluation Workshop (ORE) 2013
# Reasoner Competition Benchmark Script v1.5
# Last updated: 12-Jul-13
# 
# To test your system you should alter the 'execReasoner' script according to your system
#
# Base folders: reasoner, ontologies, and runner scripts (change these appropriately)
# 
rbase="/Users/rafa/Documents/PhD/ORE/reasoners/"
ontbase="/Users/rafa/Documents/PhD/ORE/ontologies/"
runbase="/Users/rafa/Documents/PhD/ORE/runner/"
# 
# Using the script:
# sh start <Operation> <OntPath> <Output> <Reasoner> (<ConceptURI> | <QueryFile>)
# 	<Operation>		One of: sat | classification | consistency | query
# 	<OntologyFile>		Absolute ontology file path
#	<Output>		Output folder path
# 	<Reasoner>		Reasoner folder name (rooted at rbase above) which should contain an 'execReasoner' script
# 		ORE-2013 reasoners: basevisor | elephant | elk | fact | hermit | jcel | jfact | konclude | more-hermit | more-pellet | snorocket | treasoner | trowl | wsclassifier
# 	<ConceptURI>		Concept URI, as declared in the ontology
# 	<QueryFile>		Absolute query file path
# 
# To start with, print the parameters back as they are parsed
# 
if [ $# -gt 1 ]; then
	echo "$# parameters given: $*"
	echo "	Operation: $1"
	echo "	Ontology Filepath: $2"
    echo "	Reasoner: $4"
	if [ $# -gt 4 ]; then
		if [ "$1" = "sat" ]; then
			echo "	Concept URI: $5"
		elif [ "$1" = "query" ]; then
			echo "	Query Filepath: $5"
		fi
	fi
	ontname=`basename $2`
	out="$3/$4_-_$1_-_$ontname"
	if [ "$1" = "sat" -o "$1" = "consistency" ]; then
		out="$out.csv"
	elif [ "$1" = "classification" ]; then
		out="$out.owl"
	fi
    echo "	Output Folder: $out"
	# 	
	# Validate the parameters, i.e., whether:
	# 1) Given (ontology and/or query) files exist
	# 2) Operation is one of the specified ones
	# 3) Concept exists in the ontology signature
	# 
	echo "Verifying parameters..."
	chk=$(java -jar InputVerifier.jar $1 $2 $out $5)
	if [ "$chk" = "Valid parameters" ]; then
		echo "	Parameters are valid"
		#
		# Restrict system resources
		# Max memory: 9GB
		# Max time: 7 minutes (5 minute timeout + 2 minutes allowance)
		#
		ulimit -v 9961472
		ulimit -t 420
		# 
		# Execute reasoner with given parameters. Once the operation
		# is completed, the wall clock time difference is printed
		# 
		echo "Executing reasoner..."
		cd "$rbase/$4"
		start_time=`date +%s`
		rout=$(./execReasoner $1 $2 $out $5)
		end_time=`date +%s`
		duration=`expr $end_time - $start_time`
		output="$rout \nDuration: $duration"
		echo "$rout"
		echo "$output" > $out"_log"
		echo "Finished. Total wall clock duration: $duration second(s)"
		# 		
		# Handle output
		# 
		echo "Verifying output..."
		cd "$runbase" && java -jar OutputHandler.jar "$rbase/$4/"$out"_log" $1 $2 $out $4 $5
		echo "Done"
	else
		echo "$chk"
	fi
else
	echo "! Insufficient or no parameters given"
	echo ""
	echo "Usage:	sh start <Operation> <OntPath> <Output> <Reasoner> (<ConceptURI> | <QueryFile>)"
	echo "	<Operation>	One of: sat | classification | consistency | query"
	echo "	<OntologyFile>	Ontology file path"
	echo "	<Output>	Output file path"
	echo "	<Reasoner>	Reasoner folder name (rooted at rbase) which should contain an 'execReasoner' script"
	echo "	<ConceptURI>	Concept URI, as declared in the ontology"
	echo "	<QueryFile>	Absolute query file path"
	echo ""
fi