#!/bin/bash
# 
# OWL Reasoner Evaluation Workshop (ORE) 2013
# Last updated: 20-Jul-13
# 
base="/Users/rafa/Documents/PhD/workspace/ore-framework/test/base"
ontbase="$base/ontologies"
satbase="$ontbase/sat"
rbase="$base/reasoners"
# 
# Using the script:
#
# sh startResultVerification <Operation> <Ontology> <Output> <Profile>
#
# 	<Operation>		One of: sat | classification | consistency
# 	<Ontology>	Absolute ontology file path
#	<Output>		Output folder (absolute path)
# 	<Profile>		Ontology's profile
# 
declare -a reasoners=(basevisor chainsaw elephant elk-loading-counted elk-loading-not-counted fact hermit jcel jfact konclude more-hermit more-pellet snorocket treasoner trowl wsclassifier)		
args=("$@") 
ELEMENTS=${#args[@]}
if [ $ELEMENTS -gt 2 ]; then
	ext=""
	if [ "$1" = "classification" ]; then
		ext="owl"
	else
		ext="csv"
	fi	
	filename=`basename $2`
	echo "Ontology: $filename"
	echo "Ontology filepath: $2"
	echo "Operation: $1"
	echo "Output folder: $3"
	cmd=""
	for reasoner in ${reasoners[@]}
	do
		cmd="$cmd $rbase/$reasoner/output/$filename/$1.$ext"
	done
	satfile="nothing" # irrelevant for classification or consistency
	if [ "$1" = "sat" ]; then
		satfile="$satbase/$4/$filename"_sat.txt
	fi			
	java -Xmx10G -jar ResultChecker.jar $1 $3 $satfile $cmd
	printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
else
	echo "! Insufficient or no parameters given"
	echo ""
	echo "Usage:	sh startResultVerification <Operation> <Ontology> <Output> <Profile>"
	echo "	<Operation>		One of: sat | classification | consistency"
	echo "	<Ontology>		Absolute ontology file path"
	echo "	<Output>		Output folder (absolute path)"
	echo "	<Profile>		Ontology's profile"
	echo ""
fi